name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOTNET_VERSION: "10.x"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore SchoolAccount.ApiTemplate.slnx

      - name: Build
        run: dotnet build SchoolAccount.ApiTemplate.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test --settings ./tests/xplat.runsettings --collect:"XPlat Code Coverage" SchoolAccount.ApiTemplate.slnx --configuration Release --no-restore --no-build

      - name: List coverage files
        run: |
          ls -R ./tests/*/TestResults/*/*.cobertura.xml
          mv ./tests/*/TestResults/*/*.cobertura.xml ./arch.cobertura.xml
      - name: Upload code coverage
        if: always()
        uses: actions/upload-code-coverage@v1
        with:
          file: ./arch.cobertura.xml
          language: csharp
          label: Code Coverage

      - name: Publish
        run: dotnet publish SchoolAccount.ApiTemplate.slnx --configuration Release --no-restore --no-build
